alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias uudu='sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y && sudo apt-get autoclean -y'
alias python='python3'
alias Psychopartner='ssh -p 22122 stephan@176.96.139.244'
alias Hyak='ssh sthagel@mox.hyak.uw.edu'
alias julia='~/programs/julia/julia'
alias jaxodraw='java -jar $HOME/programs/jaxodraw-2.1-0/jaxodraw-2.1-0.jar'
alias cmdebug='cmake -DCMAKE_BUILD_TYPE=Debug ..'
alias cmrelease='cmake -DCMAKE_BUILD_TYPE=Release ..'
alias vlang='~/programs/vlang/v'
alias grepi='grep -i'
alias hisgrep='history | grep -i'
alias psgrep='ps -A | grep -i'
